--- #YAML:1.0
name: Catalyst-Plugin-Email-Japanese
version: 0.03
author:
  - Daisuke Murase <typester@cpan.org>
abstract: Send Japanese emails with Catalyst
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
