---
name: Catalyst-Plugin-Email-Japanese
version: 0.07
author:
  - 'Daisuke Murase <typester@cpan.org>'
abstract: Send Japanese emails with Catalyst
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Catalyst: 5.30
  MIME::Lite::TT::HTML::Japanese: 0.05
  MIME::Lite::TT::Japanese: 0
recommends:
  Template::Provider::Encoding: 0
provides:
  Catalyst::Plugin::Email::Japanese:
    file: lib/Catalyst/Plugin/Email/Japanese.pm
    version: 0.07
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
